In [37]:
import numpy as np 
import pandas as pd

my_array = np.array([16, 24, 36, 44, 52, 26, 37, 34, 56, 78]) 

memory_addresses = [hex(id(element)) for element in my_array]
values = my_array.flatten()

# Create a DataFrame
data = {'Memory Location': memory_addresses, 'Value': values}


df = pd.DataFrame(data)
df

Memory Location  Value
0   0x2b4c9b50650     16
1   0x2b4c9b50630     24
2   0x2b4c9b50650     36
3   0x2b4c9b50630     44
4   0x2b4c9b50650     52
5   0x2b4c9b50830     26
6   0x2b4c9b50650     37
7   0x2b4c9b50830     34
8   0x2b4c9b50650     56
9   0x2b4c9b50830     78

In [45]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

4

In [46]:
np.zeros(3)

array([0., 0., 0.])

In [47]:
np.ones(4)

array([1., 1., 1., 1.])

In [50]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [53]:
np.linspace(0,100, 21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [40]:
my_list = [16, 24, 36, 44, 52, 26, 37, 34, 56, 78]

memory_addresses = [hex(id(element)) for element in my_list]
# Create a DataFrame
data = {'Memory Location': memory_addresses, 'Value': my_list}

df = pd.DataFrame(data)
df

Memory Location  Value
0   0x2b4aa796b10     16
1   0x2b4aa796c10     24
2   0x2b4aa796d90     36
3   0x2b4aa796e90     44
4   0x2b4aa796f90     52
5   0x2b4aa796c50     26
6   0x2b4aa796db0     37
7   0x2b4aa796d50     34
8   0x2b4aa7c5050     56
9   0x2b4aa7c5310     78

In [42]:
my_list = [16, 24, 36, 'name', 52, 'age']

memory_addresses = [hex(id(element)) for element in my_list]
# Create a DataFrame
data = {'Memory Location': memory_addresses, 'Value': my_list}

df = pd.DataFrame(data)
df

Memory Location Value
0   0x2b4aa796b10    16
1   0x2b4aa796c10    24
2   0x2b4aa796d90    36
3   0x2b4aa7c8130  name
4   0x2b4aa796f90    52
5   0x2b4c9c0e270   age